version: '3.8'
services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1111
            POSTGRES_DB: zno_db
        ports:
            - "5432:5432"
        networks:
            - network
            
    db_norm:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1111
            POSTGRES_DB: zno_db_norm
        ports:
            - "5050:5050"
        networks:
            - network
          
    app:
        build: ./app/
        depends_on:
          db:
            condition: service_started
          db_norm:
            condition: service_started
        volumes:
            - ./app:/usr/src/app
        networks:
            - network
            
    web:
        build: ./web/
        depends_on:
          app:
            condition: service_completed_successfully
        volumes:
            - ./web:/usr/src/web
        networks:
            - network
            
networks:
    network: